apiVersion: v1
kind: Service
metadata:
  name: hms-frontend-service
  labels:
    app: hms-frontend
spec:
  type: LoadBalancer
  selector:
    app: hms-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
